-- starter predefined exercise catalog (created_by NULL, visible to everyone)
INSERT INTO exercises (name, muscle_group, equipment, is_custom) VALUES
  ('Barbell Bench Press', 'chest', 'free-weight', false),
  ('Incline Dumbbell Press', 'chest', 'free-weight', false),
  ('Cable Fly', 'chest', 'cable', false),
  ('Overhead Press', 'shoulders', 'free-weight', false),
  ('Lateral Raise', 'shoulders', 'free-weight', false),
  ('Rear Delt Fly', 'shoulders', 'cable', false),
  ('Barbell Row', 'back', 'free-weight', false),
  ('Lat Pulldown', 'back', 'cable', false),
  ('Seated Cable Row', 'back', 'cable', false),
  ('Pull-Up', 'back', 'bodyweight-loadable', false),
  ('Barbell Curl', 'biceps', 'free-weight', false),
  ('Incline Dumbbell Curl', 'biceps', 'free-weight', false),
  ('Cable Triceps Pushdown', 'triceps', 'cable', false),
  ('Overhead Triceps Extension', 'triceps', 'free-weight', false),
  ('Back Squat', 'quads', 'free-weight', false),
  ('Leg Press', 'quads', 'machine', false),
  ('Romanian Deadlift', 'hamstrings', 'free-weight', false),
  ('Leg Curl', 'hamstrings', 'machine', false),
  ('Hip Thrust', 'glutes', 'free-weight', false),
  ('Standing Calf Raise', 'calves', 'machine', false),
  ('Cable Crunch', 'abs', 'cable', false),
  ('Hanging Leg Raise', 'abs', 'bodyweight', false);
