/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/callback': RouteRecordInfo<
      '/auth/callback',
      '/auth/callback',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/mesocycles/build': RouteRecordInfo<
      '/mesocycles/build',
      '/mesocycles/build',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/mesocycles/plan': RouteRecordInfo<
      '/mesocycles/plan',
      '/mesocycles/plan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/workouts/[id]': RouteRecordInfo<
      '/workouts/[id]',
      '/workouts/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/workouts/list': RouteRecordInfo<
      '/workouts/list',
      '/workouts/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/callback.vue': {
      routes:
        | '/auth/callback'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/mesocycles/build.vue': {
      routes:
        | '/mesocycles/build'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/mesocycles/plan.vue': {
      routes:
        | '/mesocycles/plan'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/workouts/[id].vue': {
      routes:
        | '/workouts/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/workouts/list.vue': {
      routes:
        | '/workouts/list'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
